version = 3.8.3

maxColumn = 96

docstrings.style = preserve

indent.callSite = 2
indent.defnSite = 2
indent.extendSite = 2

align.preset = none
align.openParenCallSite = false
align.openParenDefnSite = false

optIn.configStyleArguments = true

newlines.topLevelStatementBlankLines = [
  { blanks { before = 1 } }
]
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly

rewrite.rules = [
  SortModifiers
  SortImports
]

rewrite.sortModifiers.order = [
  "private", "protected", "final", "override", "abstract", "sealed", "implicit", "lazy"
]

# Most subprojects use Scala 3; override to scala213 for the Scala 2.x benchmarks.
runner.dialect = scala3

fileOverride {
  "glob:**/{apache-spark,neo4j,scala-sat,twitter-finagle,actors-reactors}/src/**/*.scala" {
    runner.dialect = scala213
  }
  "glob:**/*.sbt" {
    runner.dialect = scala213
    newlines.topLevelStatementBlankLines = []
  }
  "glob:**/project/*.scala" {
    runner.dialect = scala213
  }
}
